### ISSUE TITLE
SSL Issue

### ISSUE THREAD

**Issue by GettingTechnicl** [mlan/docker-postfix#1]
when my relay is attempting to negotiate connection inbound, I receive the following issues that seem to be SSL related. Any idea what could assist in resolving this? 

Port 993:
`Jan 15 01:22:36 kopano-gateway[1166]: Accepted connection from 162.216.242.29:57980
Jan 15 01:22:36 kopano-gateway[1166]: Starting worker thread for IMAPs request
Jan 15 01:22:36 kopano-gateway[1166]: ECChannel::HrEnableTLS(): min TLS version 0x303
Jan 15 01:22:36 kopano-gateway[1166]: ECChannel::HrEnableTLS(): max TLS version 0x0
Jan 15 01:22:36 kopano-gateway[1166]: ECChannel::HrEnableTLS(): TLS flags 0xc0520854
Jan 15 01:22:36 kopano-gateway[1166]: ECChannel::HrEnableTLS(): SSL_accept failed: 5
Jan 15 01:22:36 kopano-gateway[1166]: Unable to negotiate SSL connection with 000.216.000.29:57980
Jan 15 01:22:36 kopano-gateway[1166]: Client 000.216.000.29:57980 thread exiting
`
Port 587:
`Jan 15 01:26:17 postfix/smtps/smtpd[1681]: warning: TLS library problem: error:0A000126:SSL routines::unexpected eof while reading:ssl/record/rec_layer_s3.c:320:`

**Comment by mlan** [comment]
@GettingTechnicl You are mentioning both IMAPS and Submission connections which is handled by different pieces of software. So it not obvious what you are trying to achieve.

I suggest you try to run the demo and test SSL with it. Once the demo has been initiated you can experiment with the following to understand the SSL components better.

```bash
git clone https://github.com/mlan/docker-postfix.git
cd docker-postfix/demo
make init
make app-test_tls
make app-test_imaps
```
